#!/usr/bin/env python3
"""Generate a standalone, offline HTML overview. No network requests or dependencies."""
import csv,json,html
from pathlib import Path
R=Path(__file__).resolve().parents[1]
a=json.loads((R/'data/processed/audit.json').read_text())
def table(rows, cols, ident=''):
 return '<table '+('id="'+ident+'"' if ident else '')+'><thead><tr>'+''.join('<th>'+html.escape(label)+'</th>' for key,label in cols)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(str(r[key]))+'</td>' for key,label in cols)+'</tr>' for r in rows)+'</tbody></table>'
systems=list(csv.DictReader((R/'data/processed/system-summary.csv').open()))
summary=[dict(program=p,**v) for p,v in a['programs'].items()]
body='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Oregon PFAS · 监测证据</title><style>
body{font:16px/1.65 system-ui,sans-serif;color:#18363b;background:#f5f7f3;margin:0}main{max-width:1120px;margin:auto;padding:36px 24px}h1{font-size:42px;line-height:1.15}h2{margin-top:36px}p{max-width:900px}a{color:#086f72}header{border-top:5px solid #087e80;padding-top:20px}.eyebrow{letter-spacing:2px;color:#466a65;font-size:13px}.note{padding:18px;background:#fff2d9;border-left:4px solid #bf8826}table{border-collapse:collapse;width:100%;background:white;font-size:14px}th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #dce4df}th{background:#e3efea;position:sticky;top:0}input,select{font:inherit;padding:10px;border:1px solid #96b5ac;border-radius:4px;margin:0 10px 12px 0}section.scroll{overflow:auto;max-height:480px;border:1px solid #dce4df}footer{margin-top:36px;color:#52706c}code{background:#e3efea;padding:2px 5px}.wrap{overflow:auto}</style><main><p><a href="index.html">← 返回全屏地图</a></p><header><div class="eyebrow">PFAS / OREGON / SNAPSHOT 2026-09-06</div><h1>监测怎样影响我们<br>看见的污染？</h1><p>公共饮用水 PFAS 数据底座。保留检出与未检出、方法和报告限，先检验可比性，再研究覆盖与制度改进。</p></header>
<p class="note"><strong>范围：</strong>本版覆盖 EPA UCMR3、UCMR5 中 State=OR 的 PFAS 记录。OHA 专项逐条结果尚未获取；没有全州系统名录分母，因此不能据此判断全州监测覆盖率。未检出不等于零，检出不等于违法。</p><h2>已补齐的 EPA 数据</h2><div class="wrap">'''
body+=table(summary,[('program','轮次'),('analytical_records','分析记录'),('systems','供水系统'),('analytes','PFAS 种类'),('detected_records','检出记录'),('systems_with_detections','有检出的系统')])
body+='''</div><p>Owen 原来的 92 条检出全部匹配官方数据；新增 UCMR5 21,169 条低于报告限记录。跨轮次共有 133 个不同系统。分析记录数不等于水样瓶数。</p><h2>如果仍用旧报告限，会看到多少检出？</h2><div class="wrap">'''
body+=table(a['threshold_comparison'],[('analyte','分析物'),('ucmr3_mrl_ng_l','旧 MRL（ng/L）'),('ucmr5_detected_at_own_mrl','新轮次自身 MRL 检出'),('ucmr5_at_or_above_ucmr3_mrl','达到旧 MRL')])
body+='''</div><p>PFOA 和 PFOS 的新轮次检出均低于旧报告限。此表是阈值敏感性比较；系统、点位与年份同时变化，不能据此估计污染趋势。详见 <a href="docs/research-strategy.md">研究策略</a>。</p><h2>查看供水系统</h2><label>轮次 <select id="program"><option value="">全部</option><option>UCMR3</option><option>UCMR5</option></select></label><label>名称或 ID <input id="search" type="search" placeholder="例如 Portland 或 OR410…"></label><span id="count" aria-live="polite"></span><section class="scroll">'''
body+=table(systems,[('program','轮次'),('pws_id','PWSID'),('pws_name','系统名称'),('analytical_records','分析记录'),('detected_records','检出'),('analytes','分析物'),('first_collection','最早日期'),('last_collection','最晚日期')],'systems')
body+='''</section><h2>下载与复核</h2><p><a href="data/processed/oregon-pfas-results.csv" download>结果主表 CSV</a> · <a href="data/processed/system-summary.csv" download>系统汇总 CSV</a> · <a href="data/processed/analyte-method-limits.csv" download>方法与报告限 CSV</a> · <a href="data/processed/common-analyte-threshold-comparison.csv" download>共同阈值 CSV</a></p><p><a href="docs/data-quality.md">数据质量与待补清单</a> · <a href="README.md">复现与 GitHub 同步</a> · <a href="notebooks/audit.ipynb">审计 notebook</a></p><p class="note">日期说明：UCMR5 官方文件含 108 条 2026 年采样记录，最晚 2026-06-08，已原样保留。州级 2021 年系统名单仅为计划名单，未当作完成证明。服务区/ZIP 质心未用于人口暴露推断。</p><footer>来源：<a href="https://www.epa.gov/dwucmr/occurrence-data-unregulated-contaminant-monitoring-rule">EPA 官方 UCMR 下载</a>；Owen 原始检出子集用于逐条核对。离线报告，不调用第三方服务。</footer></main><script>
const rows=[...document.querySelectorAll('#systems tbody tr')],p=document.querySelector('#program'),q=document.querySelector('#search');function filter(){let n=0;rows.forEach(r=>{const show=(!p.value||r.cells[0].textContent===p.value)&&r.textContent.toLowerCase().includes(q.value.toLowerCase());r.hidden=!show;if(show)n++});document.querySelector('#count').textContent=n+' 条轮次 × 系统记录'}p.addEventListener('change',filter);q.addEventListener('input',filter);filter();</script></html>'''
(R/'report.html').write_text(body)
print('Built report.html; system rows:',len(systems))
