$ErrorActionPreference = 'Stop'
$root=$PSScriptRoot
$analysisDir=Join-Path $root 'data\analysis'
New-Item -ItemType Directory -Force -Path $analysisDir | Out-Null

function To-Number($value){$n=0.0;if([double]::TryParse(([string]$value -replace ',',''),[Globalization.NumberStyles]::Float,[Globalization.CultureInfo]::InvariantCulture,[ref]$n)){return $n};return $null}
function Percent($part,$total){if($null -eq $part -or $null -eq $total -or $total -le 0){return $null};return 100.0*$part/$total}
function Mean($values){$a=@($values|Where-Object{$null-ne $_});if(-not $a.Count){return $null};return ($a|Measure-Object -Average).Average}

function Read-AcsTable([string]$path){
    $reader=[IO.StreamReader]::new($path);try{$header=$reader.ReadLine().Split('|');$rows=[Collections.Generic.List[object]]::new();while(-not $reader.EndOfStream){$line=$reader.ReadLine();if($line.StartsWith('1400000US06')-or$line.StartsWith('1400000US41')-or$line.StartsWith('1400000US53')){$parts=$line.Split('|');$row=@{};for($i=0;$i-lt$header.Count;$i++){$row[$header[$i]]=$parts[$i]};$rows.Add($row)}};return $rows}finally{$reader.Dispose()}
}

$demographics=@{}
foreach($row in Read-AcsTable (Join-Path $analysisDir 'acs-bulk\acsdt5y2024-b01003.dat')){
    $geoid=$row.GEO_ID.Substring($row.GEO_ID.Length-11);$demographics[$geoid]=[ordered]@{tract_geoid=$geoid;state_fips=$geoid.Substring(0,2);county_fips=$geoid.Substring(2,3);tract_code=$geoid.Substring(5,6);total_population=(To-Number $row.B01003_E001);total_population_moe=(To-Number $row.B01003_M001)}
}
foreach($row in Read-AcsTable (Join-Path $analysisDir 'acs-bulk\acsdt5y2024-b03002.dat')){
    $geoid=$row.GEO_ID.Substring($row.GEO_ID.Length-11);if(-not$demographics.ContainsKey($geoid)){continue};$d=$demographics[$geoid];$total=To-Number $row.B03002_E001;$white=To-Number $row.B03002_E003;$d.race_ethnicity_total=$total;$d.white_non_hispanic=$white;$d.black_non_hispanic=To-Number $row.B03002_E004;$d.aian_non_hispanic=To-Number $row.B03002_E005;$d.asian_non_hispanic=To-Number $row.B03002_E006;$d.nhpi_non_hispanic=To-Number $row.B03002_E007;$d.other_race_non_hispanic=To-Number $row.B03002_E008;$d.multiracial_non_hispanic=To-Number $row.B03002_E009;$d.hispanic_or_latino=To-Number $row.B03002_E012;$d.people_of_color=if($null-ne$total-and$null-ne$white){$total-$white}else{$null};$d.people_of_color_pct=Percent $d.people_of_color $total;$d.white_non_hispanic_pct=Percent $white $total;$d.black_non_hispanic_pct=Percent $d.black_non_hispanic $total;$d.aian_non_hispanic_pct=Percent $d.aian_non_hispanic $total;$d.asian_non_hispanic_pct=Percent $d.asian_non_hispanic $total;$d.nhpi_non_hispanic_pct=Percent $d.nhpi_non_hispanic $total;$d.other_race_non_hispanic_pct=Percent $d.other_race_non_hispanic $total;$d.multiracial_non_hispanic_pct=Percent $d.multiracial_non_hispanic $total;$d.hispanic_or_latino_pct=Percent $d.hispanic_or_latino $total
}
foreach($row in Read-AcsTable (Join-Path $analysisDir 'acs-bulk\acsdt5y2024-b19013.dat')){
    $geoid=$row.GEO_ID.Substring($row.GEO_ID.Length-11);if(-not$demographics.ContainsKey($geoid)){continue};$income=To-Number $row.B19013_E001;$moe=To-Number $row.B19013_M001;$demographics[$geoid].median_household_income=if($income-ge0){$income}else{$null};$demographics[$geoid].median_household_income_moe=if($moe-ge0){$moe}else{$null}
}

function Get-Bounds($geometry){$minX=[double]::PositiveInfinity;$minY=[double]::PositiveInfinity;$maxX=[double]::NegativeInfinity;$maxY=[double]::NegativeInfinity;if($geometry.type-eq'Polygon'){foreach($ring in $geometry.coordinates){foreach($p in $ring){$x=[double]$p[0];$y=[double]$p[1];$minX=[Math]::Min($minX,$x);$maxX=[Math]::Max($maxX,$x);$minY=[Math]::Min($minY,$y);$maxY=[Math]::Max($maxY,$y)}}}else{foreach($polygon in $geometry.coordinates){foreach($ring in $polygon){foreach($p in $ring){$x=[double]$p[0];$y=[double]$p[1];$minX=[Math]::Min($minX,$x);$maxX=[Math]::Max($maxX,$x);$minY=[Math]::Min($minY,$y);$maxY=[Math]::Max($maxY,$y)}}}};@($minX,$minY,$maxX,$maxY)}
function Test-Ring($ring,[double]$x,[double]$y){$inside=$false;$j=$ring.Count-1;for($i=0;$i-lt$ring.Count;$i++){$xi=[double]$ring[$i][0];$yi=[double]$ring[$i][1];$xj=[double]$ring[$j][0];$yj=[double]$ring[$j][1];if((($yi-gt$y)-ne($yj-gt$y))-and($x-lt($xj-$xi)*($y-$yi)/(($yj-$yi)+1e-30)+$xi)){$inside=-not$inside};$j=$i};$inside}
function Test-Polygon($polygon,[double]$x,[double]$y){if(-not(Test-Ring $polygon[0] $x $y)){return $false};for($i=1;$i-lt$polygon.Count;$i++){if(Test-Ring $polygon[$i] $x $y){return $false}};return $true}
function Test-Geometry($geometry,[double]$x,[double]$y){if($geometry.type-eq'Polygon'){return Test-Polygon $geometry.coordinates $x $y};foreach($polygon in $geometry.coordinates){if(Test-Polygon $polygon $x $y){return $true}};return $false}

$stateConfig=@(
    @{Name='California';Fips='06';Tracts='data\california\california-census-tracts.geojson'},
    @{Name='Oregon';Fips='41';Tracts='data\oregon\oregon-census-tracts.geojson'},
    @{Name='Washington';Fips='53';Tracts='data\washington\washington-census-tracts.geojson'}
)
$stations=(Get-Content (Join-Path $root 'data\west-coast-pfas-stations.geojson') -Raw|ConvertFrom-Json).features
$joined=[Collections.Generic.List[object]]::new();$unmatched=[Collections.Generic.List[object]]::new();$stationId=0
foreach($state in $stateConfig){
    $tractData=Get-Content (Join-Path $root $state.Tracts) -Raw|ConvertFrom-Json;$grid=@{}
    foreach($feature in $tractData.features){$bounds=Get-Bounds $feature.geometry;$record=[pscustomobject]@{geoid=[string]$feature.properties.GEOID;geometry=$feature.geometry;minX=$bounds[0];minY=$bounds[1];maxX=$bounds[2];maxY=$bounds[3]};for($gx=[Math]::Floor($record.minX);$gx-le[Math]::Floor($record.maxX);$gx++){for($gy=[Math]::Floor($record.minY);$gy-le[Math]::Floor($record.maxY);$gy++){$key="$gx,$gy";if(-not$grid.ContainsKey($key)){$grid[$key]=[Collections.Generic.List[object]]::new()};$grid[$key].Add($record)}}}
    foreach($feature in $stations|Where-Object{$_.properties.map_state-eq$state.Name}){$stationId++;$x=[double]$feature.geometry.coordinates[0];$y=[double]$feature.geometry.coordinates[1];$key="$([Math]::Floor($x)),$([Math]::Floor($y))";$match=$null;foreach($candidate in @($grid[$key])){if($x-ge$candidate.minX-and$x-le$candidate.maxX-and$y-ge$candidate.minY-and$y-le$candidate.maxY-and(Test-Geometry $candidate.geometry $x $y)){$match=$candidate;break}};if(-not$match){$unmatched.Add([pscustomobject]@{station_id=$stationId;state=$state.Name;site_name=$feature.properties.site_name;longitude=$x;latitude=$y});continue};$d=$demographics[$match.geoid];$joined.Add([pscustomobject][ordered]@{station_id=$stationId;tract_geoid=$match.geoid;state_fips=$state.Fips;state_name=$state.Name;county_fips=$match.geoid.Substring(2,3);tract_code=$match.geoid.Substring(5,6);site_name=$feature.properties.site_name;industry=$feature.properties.industry;matrix=if($feature.properties.matrix){$feature.properties.matrix}else{$feature.properties.matrix_type};sample_year=$feature.properties.year;longitude=$x;latitude=$y;pfoa=(To-Number $feature.properties.pfoa);pfos=(To-Number $feature.properties.pfos);total_pfas=(To-Number $feature.properties.total_pfas);reported_pfas_level=(To-Number $feature.properties.pfas_level);total_population=$d.total_population;people_of_color=$d.people_of_color;people_of_color_pct=$d.people_of_color_pct;white_non_hispanic_pct=$d.white_non_hispanic_pct;black_non_hispanic_pct=$d.black_non_hispanic_pct;aian_non_hispanic_pct=$d.aian_non_hispanic_pct;asian_non_hispanic_pct=$d.asian_non_hispanic_pct;nhpi_non_hispanic_pct=$d.nhpi_non_hispanic_pct;other_race_non_hispanic_pct=$d.other_race_non_hispanic_pct;multiracial_non_hispanic_pct=$d.multiracial_non_hispanic_pct;hispanic_or_latino_pct=$d.hispanic_or_latino_pct;median_household_income=$d.median_household_income})}
    $tractData=$null;[GC]::Collect()
}

$joined|Export-Csv (Join-Path $analysisDir 'west-coast-pfas-stations-with-tract-demographics.csv') -NoTypeInformation -Encoding UTF8
$unmatched|Export-Csv (Join-Path $analysisDir 'west-coast-pfas-stations-unmatched.csv') -NoTypeInformation -Encoding UTF8
$joinedFeatures=@($joined|ForEach-Object{[ordered]@{type='Feature';geometry=[ordered]@{type='Point';coordinates=@([double]$_.longitude,[double]$_.latitude)};properties=$_}})
[ordered]@{type='FeatureCollection';crs=@{type='name';properties=@{name='EPSG:4326'}};features=$joinedFeatures}|ConvertTo-Json -Depth 12 -Compress|Set-Content (Join-Path $analysisDir 'west-coast-pfas-stations-with-tract-demographics.geojson') -Encoding UTF8
$demographics.Values|ForEach-Object{[pscustomobject]$_}|Export-Csv (Join-Path $analysisDir 'acs-2024-tract-demographics.csv') -NoTypeInformation -Encoding UTF8

$compoundFields=[ordered]@{PFOA='pfoa';PFOS='pfos';TOTAL_PFAS='total_pfas';REPORTED_PFAS_LEVEL='reported_pfas_level'};$compoundCounts=@{};foreach($compound in $compoundFields.Keys){$field=$compoundFields[$compound];$compoundCounts[$compound]=@($joined|Where-Object{$null-ne$_.$field}).Count}
$primaryCompound=@('PFOA','PFOS')|Sort-Object{$compoundCounts[$_]}-Descending|Select-Object -First 1;$primaryField=$compoundFields[$primaryCompound]
$groups=$joined|Group-Object tract_geoid;$byTract=@{};$long=[Collections.Generic.List[object]]::new()
foreach($group in $groups){$rows=@($group.Group);foreach($compound in $compoundFields.Keys){$field=$compoundFields[$compound];$values=@($rows|ForEach-Object{$_.$field}|Where-Object{$null-ne$_});if($values.Count){$long.Add([pscustomobject]@{tract_geoid=$group.Name;state_fips=$group.Name.Substring(0,2);compound=$compound;average_concentration=Mean $values;observation_count=$values.Count;station_count=@($rows.station_id|Sort-Object -Unique).Count})}};$byTract[$group.Name]=@{station_count=@($rows.station_id|Sort-Object -Unique).Count;measurement_record_count=$rows.Count;pfoa_average=Mean @($rows.pfoa);pfoa_observation_count=@($rows|Where-Object{$null-ne$_.pfoa}).Count;pfos_average=Mean @($rows.pfos);pfos_observation_count=@($rows|Where-Object{$null-ne$_.pfos}).Count;total_pfas_average=Mean @($rows.total_pfas);total_pfas_observation_count=@($rows|Where-Object{$null-ne$_.total_pfas}).Count;reported_pfas_average=Mean @($rows.reported_pfas_level);reported_pfas_observation_count=@($rows|Where-Object{$null-ne$_.reported_pfas_level}).Count;primary_pfas_measure=$primaryCompound;primary_pfas_average=Mean @($rows|ForEach-Object{$_.$primaryField});primary_pfas_observation_count=@($rows|Where-Object{$null-ne$_.$primaryField}).Count}}
$long|Export-Csv (Join-Path $analysisDir 'west-coast-tract-compound-averages.csv') -NoTypeInformation -Encoding UTF8

$tractTable=[Collections.Generic.List[object]]::new();$mapLookup=[ordered]@{}
foreach($geoid in $demographics.Keys|Sort-Object){$d=$demographics[$geoid];$a=$byTract[$geoid];if(-not$a){$a=@{station_count=0;measurement_record_count=0;pfoa_average=$null;pfoa_observation_count=0;pfos_average=$null;pfos_observation_count=0;total_pfas_average=$null;total_pfas_observation_count=0;reported_pfas_average=$null;reported_pfas_observation_count=0;primary_pfas_measure=$primaryCompound;primary_pfas_average=$null;primary_pfas_observation_count=0}};$row=[ordered]@{};foreach($k in $d.Keys){$row[$k]=$d[$k]};foreach($k in $a.Keys){$row[$k]=$a[$k]};$tractTable.Add([pscustomobject]$row);$mapLookup[$geoid]=[ordered]@{total_population=$d.total_population;people_of_color_pct=$d.people_of_color_pct;white_non_hispanic_pct=$d.white_non_hispanic_pct;black_non_hispanic_pct=$d.black_non_hispanic_pct;aian_non_hispanic_pct=$d.aian_non_hispanic_pct;asian_non_hispanic_pct=$d.asian_non_hispanic_pct;nhpi_non_hispanic_pct=$d.nhpi_non_hispanic_pct;other_race_non_hispanic_pct=$d.other_race_non_hispanic_pct;multiracial_non_hispanic_pct=$d.multiracial_non_hispanic_pct;hispanic_or_latino_pct=$d.hispanic_or_latino_pct;median_household_income=$d.median_household_income;station_count=$a.station_count;measurement_record_count=$a.measurement_record_count;pfoa_average=$a.pfoa_average;pfoa_observation_count=$a.pfoa_observation_count;pfos_average=$a.pfos_average;pfos_observation_count=$a.pfos_observation_count;primary_pfas_measure=$primaryCompound;primary_pfas_average=$a.primary_pfas_average;primary_pfas_observation_count=$a.primary_pfas_observation_count}}
$tractTable|Export-Csv (Join-Path $analysisDir 'west-coast-tract-pfas-demographics.csv') -NoTypeInformation -Encoding UTF8
$mapLookup|ConvertTo-Json -Depth 5 -Compress|Set-Content (Join-Path $analysisDir 'west-coast-tract-map-data.json') -Encoding UTF8
[ordered]@{created_utc=(Get-Date).ToUniversalTime().ToString('o');acs_vintage='2020-2024 ACS 5-year';tracts=$demographics.Count;stations_input=$stations.Count;stations_matched=$joined.Count;stations_unmatched=$unmatched.Count;monitored_tracts=$groups.Count;compound_observation_counts=$compoundCounts;primary_inventory_compound_for_display=$primaryCompound;concentration_comparability='Not harmonized across states; see analysis/comparability'}|ConvertTo-Json -Depth 5|Set-Content (Join-Path $analysisDir 'spatial-join-summary.json') -Encoding UTF8
Get-Content (Join-Path $analysisDir 'spatial-join-summary.json')
